### ISSUE TITLE
How to properly implement resolvers?

### ISSUE THREAD

**Issue by manuel-mauky** [Mando75/typeorm-graphql-loader#3]
I'm having troubles getting this library to work. 
This is my (simplified) schema:
```graphql
type Query {
  projects: [Project]
}

type Project {
  id: ID!
  name: String!
  activities: [Activity]
}

type Activity {
  id: ID!
  project: Project!
}
```

The entities:

```ts
@Entity()
export class Activity {
  @PrimaryGeneratedColumn("uuid")
  id!: string

  @ManyToOne(
    type => Project,
    project => project.activities,
    { eager: true }
  )
  project!: Project
}

@Entity()
export class Project {
  @PrimaryGeneratedColumn("uuid")
  id!: string

  @Column("varchar", { length: 100, unique: true })
  name!: string

  @OneToMany(
    type => Activity,
    activity => activity.project,
    { cascade: true }
  )
  activities!: Array<Activity>
}
```

The resolver:

```ts
const resolvers: IResolvers = {
  Query: {
    projects(root: any, args: any, { loader }: Context, info: GraphQLResolveInfo): Promise<Array<Project>> {
      return loader.loadMany(Project, {}, info)
    },
  },
  Project: {
    async activities(
      project: Project,
      args: any,
      { loader }: Context,
      info: GraphQLResolveInfo
    ): Promise<Array<Activity>> {
      return loader.loadMany<Activity>(Activity, { project }, info)
    },
  },
}
```

I was first implementing my resolvers without your library but used standard TypeORM connection and everything worked as expected (but of cause with the N+1 problem) and my test cases were successful .
To solve the N+1 problem I've reworked the resolvers to use the loader.

Problem 1)
This seems to be very fragile. I have a test case that uses this test-query:

```graphql
{ 
  projects {
    id
    activities {
      id
      project {
        id
      }
    }
  }
}
```

When I execute the test 1 out of 5 times it runs successfully but most of the time there are test failures. Sometimes I get `GraphQLError: Transaction already started for the given connection, commit current transaction before starting a new one.` and when I log the sql statements I see a ROLLBACK being done. Sometimes it executes the query but some data is missing in the result (some *activities* are missing from *projects*).

Problem 2)
It seems to be not solving the N+1 problem. I have another test case that uses this query:

```graphql
{ 
  projects {
    id
    activities {
      id
    }
  }
}
```

The total number of SELECT statements here is `numberOfProjects + 1` so for example when I have 100 projects with 10 activities each it executes 101 queries. It's doing 1 SELECT on the *projects* table and 100 on the *activities* table.
If I change it to this query:

```graphql
{ 
  projects {
    id
    activities {
      id
      project {
        id
        activities {
          id
        }
      }
    }
  }
}
```
it executes 198 SELECTs.

I assume that my implementation of the resolver is wrong but I'm not sure how I should adjust it. 

I also tried to add a resolver function for ' Activity' like this:

```ts
const resolvers = {
  ...
  Activity: {
    async project(
      activity: Activity,
      args: any,
      { loader }: Context,
      info: GraphQLResolveInfo
    ): Promise<Project | undefined> {
      return loader.loadOne<Project>(Project, { activities: [activity] }, info)
    },
  },
}
```

But this wasn't solving the problem but instead now I got a timeout for the last test-case.

Can you give any hints on how to correctly implement the resolvers or where my problem is?

**Comment by Mando75** [comment]
I'll try to reproduce this on an actual database with the provided schema to see if I can dig deeper into what is going on. I do have a couple questions while I work on that.
 1. Are you running multiple tests in parallel? If so, that may be why you are getting the transaction error and the rollbacks. If all of your tests are sharing the same TypeORM database connection and trying execute multiple transactions in parallel, the TypeORM querybuilder this package uses will trigger that exception. If you are running tests in parallel, try running them in band and see if that fixes anything. If it does, then you need to change your tests so that each one has a unique TypeORM connection. 
2. Have you tested your resolvers outside of unit/request spec tests? From your issue it wasn't clear if this is only happening in the test environment or also in a normal request via something like GraphQL Playground
3. Which versions of TypeORM and Typescript are you using?

**Comment by manuel-mauky** [comment]
Thanks for your reply:

1) I was also running the tests one by one and had the same problem.
2) I haven't tested it outside of tests. I will do this tomorrow and tell you what happend.
3) TypeORM = 0.2.21, TypeScript = 3.7.3

**Comment by Mando75** [comment]
I plugged the code you provided into a new Apollo Server/TypeORM project and played around with it a bit. I can't get it to reproduce the transaction error in just a normal server environment with GraphQL Playground, but I identified why your resolvers are still giving back an N+1 query. 

The issue is that you have provided a resolver for you projects query, but also for the activities field on the Project type. As mentioned in the README, this dataloader is meant to build a join of TypeORM relations for a top level GraphQL query or field. As such, you don't need to to define a custom resolver for the Project#Activities relation. Looking at this SQL log from TypeORM, you can see that the loader performed the join in it's initial projects query. 
![image](https://user-images.githubusercontent.com/5854696/71111886-9a39c400-2187-11ea-8bc6-9f4b5cdd3294.png)
![image](https://user-images.githubusercontent.com/5854696/71111895-a1f96880-2187-11ea-9bf5-7e1b0f1a5d5f.png)

This means that it will have returned the list of projects with activities preloaded. However, because you defined a custom resolver for Project#Activities, Apollo Server ignores the loaded relation and calls the custom resolver instead. Removing that custom field resolver should fix your N+1 problem
SQL Log with only 1 query (notice the join)
![image](https://user-images.githubusercontent.com/5854696/71111953-bb9ab000-2187-11ea-8c4e-fb8f7b908460.png)
Resolvers without the custom field resolver
![image](https://user-images.githubusercontent.com/5854696/71111966-c2292780-2187-11ea-9a7f-5abf1e36a1be.png)
GraphQL response (that last project doesn't have any activities because I didn't give it any)
![image](https://user-images.githubusercontent.com/5854696/71111978-c81f0880-2187-11ea-9e52-673f196aa7c7.png)

You may want to look through the README, specifically the second paragraph of the [Gotchas](https://github.com/Mando75/typeorm-graphql-loader#gotchas-) section as it goes over a bit of how you may need to combine this with Facebook's dataloader in some cases with many-to-many relationships.

As for the transaction error you are getting in your test environment, as I said, I can't reproduce it. I know that it is an error bubbling up from TypeORM itself. The query builder in this package makes use of [TypeORM transactions](https://typeorm.io/#/transactions) to better isolate queries. From my understanding, a TypeORM connection can only run a single transaction at a time. My guess is that error is coming from how you've set up your test database connection. Could you share either your test setup or a reproduction repository so I can take a look at it further? As I mentioned, I wasn't able to replicate it in my test ApolloServer setup.

**Comment by manuel-mauky** [comment]
Thank you very much for your help. Removing the resolver for Project#activities really solves the problem with the number of queries and the transactions.
The reason why I had this resolver was that at first I was implementing the resolver with pure TypeORM and for this I needed this resolver. Then I refactored it with your library and thought that I have to keep the resolver.

Just for the reference: With the resolver for Project#activities I was able to reproduce the transaction exception also in a normal server so it's not just a problem with my test setup. Removing the resolver solves this problem. 
I assume that with such a custom resolver apollo is invoking the loader-method multiple times in parallel and therefore sometimes transactions are overlapping. If you still like to dig deeper into this I can create a repository with full test setup. However, I don't think there was a problem within your lib but just me using it wrong.

**Comment by Mando75** [comment]
Glad to hear you got it working. I'll have to see if there is some logic I can pull from TypeORM to see if there is already an open transaction so we can handle it and avoid that error. I'll put that as an item for a future version. Thanks!
